#ifndef CO_OPCODE_H
#define CO_OPCODE_H

/* Instruction opcodes for compiled code */

#define CO_NOP                               0
#define CO_ADD                               1
#define CO_SUB                               2
#define CO_MUL                               3
#define CO_DIV                               4
#define CO_MOD                               5
#define CO_SL                                6
#define CO_SR                                7
#define CO_CONCAT                            8
#define CO_BW_OR                             9
#define CO_BW_AND                           10
#define CO_BW_XOR                           11
#define CO_BW_NOT                           12
#define CO_BOOL_NOT                         13
#define CO_BOOL_XOR                         14
#define CO_IS_IDENTICAL                     15
#define CO_IS_NOT_IDENTICAL                 16
#define CO_IS_EQUAL                         17
#define CO_IS_NOT_EQUAL                     18
#define CO_IS_SMALLER                       19
#define CO_IS_SMALLER_OR_EQUAL              20
#define CO_CAST                             21
#define CO_QM_ASSIGN                        22
#define CO_ASSIGN_ADD                       23
#define CO_ASSIGN_SUB                       24
#define CO_ASSIGN_MUL                       25
#define CO_ASSIGN_DIV                       26
#define CO_ASSIGN_MOD                       27
#define CO_ASSIGN_SL                        28
#define CO_ASSIGN_SR                        29
#define CO_ASSIGN_CONCAT                    30
#define CO_ASSIGN_BW_OR                     31
#define CO_ASSIGN_BW_AND                    32
#define CO_ASSIGN_BW_XOR                    33
#define CO_PRE_INC                          34
#define CO_PRE_DEC                          35
#define CO_POST_INC                         36
#define CO_POST_DEC                         37
#define CO_ASSIGN                           38
#define CO_ASSIGN_REF                       39
#define CO_ECHO                             40
#define CO_PRINT                            41
#define CO_JMP                              42
#define CO_JMPZ                             43
#define CO_JMPNZ                            44
#define CO_JMPZNZ                           45
#define CO_JMPZ_EX                          46
#define CO_JMPNZ_EX                         47
#define CO_CASE                             48
#define CO_SWITCH_FREE                      49
#define CO_BRK                              50
#define CO_CONT                             51
#define CO_BOOL                             52
#define CO_INIT_STRING                      53
#define CO_ADD_CHAR                         54
#define CO_ADD_STRING                       55
#define CO_ADD_VAR                          56
#define CO_BEGIN_SILENCE                    57
#define CO_END_SILENCE                      58
#define CO_INIT_FCALL_BY_NAME               59
#define CO_DO_FCALL                         60
#define CO_DO_FCALL_BY_NAME                 61
#define CO_RETURN                           62
#define CO_RECV                             63
#define CO_RECV_INIT                        64
#define CO_SEND_VAL                         65
#define CO_SEND_VAR                         66
#define CO_SEND_REF                         67
#define CO_NEW                              68
#define CO_INIT_NS_FCALL_BY_NAME            69
#define CO_FREE                             70
#define CO_INIT_ARRAY                       71
#define CO_ADD_ARRAY_ELEMENT                72
#define CO_INCLUDE_OR_EVAL                  73
#define CO_UNSET_VAR                        74
#define CO_UNSET_DIM                        75
#define CO_UNSET_OBJ                        76
#define CO_FE_RESET                         77
#define CO_FE_FETCH                         78
#define CO_EXIT                             79
#define CO_FETCH_R                          80
#define CO_FETCH_DIM_R                      81
#define CO_FETCH_OBJ_R                      82
#define CO_FETCH_W                          83
#define CO_FETCH_DIM_W                      84
#define CO_FETCH_OBJ_W                      85
#define CO_FETCH_RW                         86
#define CO_FETCH_DIM_RW                     87
#define CO_FETCH_OBJ_RW                     88
#define CO_FETCH_IS                         89
#define CO_FETCH_DIM_IS                     90
#define CO_FETCH_OBJ_IS                     91
#define CO_FETCH_FUNC_ARG                   92
#define CO_FETCH_DIM_FUNC_ARG               93
#define CO_FETCH_OBJ_FUNC_ARG               94
#define CO_FETCH_UNSET                      95
#define CO_FETCH_DIM_UNSET                  96
#define CO_FETCH_OBJ_UNSET                  97
#define CO_FETCH_DIM_TMP_VAR                98
#define CO_FETCH_CONSTANT                   99
#define CO_GOTO                            100
#define CO_EXT_STMT                        101
#define CO_EXT_FCALL_BEGIN                 102
#define CO_EXT_FCALL_END                   103
#define CO_EXT_NOP                         104
#define CO_TICKS                           105
#define CO_SEND_VAR_NO_REF                 106
#define CO_CATCH                           107
#define CO_THROW                           108
#define CO_FETCH_CLASS                     109
#define CO_CLONE                           110
#define CO_INIT_METHOD_CALL                112
#define CO_INIT_STATIC_METHOD_CALL         113
#define CO_ISSET_ISEMPTY_VAR               114
#define CO_ISSET_ISEMPTY_DIM_OBJ           115
#define CO_PRE_INC_OBJ                     132
#define CO_PRE_DEC_OBJ                     133
#define CO_POST_INC_OBJ                    134
#define CO_POST_DEC_OBJ                    135
#define CO_ASSIGN_OBJ                      136
#define CO_INSTANCEOF                      138
#define CO_DECLARE_CLASS                   139
#define CO_DECLARE_INHERITED_CLASS         140
#define CO_DECLARE_FUNCTION                141
#define CO_RAISE_ABSTRACT_ERROR            142
#define CO_DECLARE_CONST                   143
#define CO_ADD_INTERFACE                   144
#define CO_DECLARE_INHERITED_CLASS_DELAYED 145
#define CO_VERIFY_ABSTRACT_CLASS           146
#define CO_ASSIGN_DIM                      147
#define CO_ISSET_ISEMPTY_PROP_OBJ          148
#define CO_HANDLE_EXCEPTION                149
#define CO_USER_OPCODE                     150
#define CO_U_NORMALIZE                     151
#define CO_JMP_SET                         152
#define CO_DECLARE_LAMBDA_FUNCTION         153

#endif
