/* Generated by re2c 0.13.5 on Wed Aug 29 10:44:19 2012 */
#line 1 "scanner.l"
#include "cobj.h"

struct scanner_globals {
    unsigned int yy_leng;
    char *yy_text;
    char *yy_cursor;
    char *yy_marker;
    char *yy_limit;
    int yy_state;
    struct arena *arena;
};

struct scanner_globals scanner_globals;

#define YYMAXFILL 9

/*** S re2c interface code ***/
#define YYCTYPE     unsigned char
#define YYFILL(n)   { if ((YYCURSOR + n) >= (YYLIMIT + YYMAXFILL)) { return 0; }}
#define YYCURSOR    scanner_globals.yy_cursor
#define YYLIMIT     scanner_globals.yy_limit
#define YYMARKER    scanner_globals.yy_marker
#define YYGETCONDITION()  scanner_globals.yy_state
#define YYSETCONDITION(s) scanner_globals.yy_state = s
#undef YYDEBUG      /* conflicts with bison */
#ifdef YY_DEBUG
# define YYDEBUG(s, c)   printf("state: %d char: %c\n", s, c)
#else
# define YYDEBUG(s, c)
#endif
#define STATE(name) yyc##name
/*** E re2c interface code ***/

/*** S emulate flex constructs */
#define BEGIN(state)    YYSETCONDITION(STATE(state))
#define YYSTATE         YYGETCONDITION()
#define yytext      ((char*)scanner_globals.yy_text)
#define yyleng      scanner_globals.yy_leng
/*** E emulate flex constructs */

#define CO_IS_OCT(c)    ((c)>='0' && (c)<='7')
#define CO_IS_HEX(c)    (((c)>='0' && (c)<='9') || ((c)>='a' && (c)<='f') || ((c)>='A' && (c)<='F'))

static void
co_scan_singlequoted_string(COStrObject *co)
{
    char *s, *t;
    char *end;

    s = t = co->co_sval;
    end = s + CO_SIZE(co);
    while (s < end) {
        if (*s == '\\') {
            s++;
            if (s >= end) {
                *t++ = '\\';
                break;
            }
            switch (*s) {
            case '\'':
                *t++ = '\'';
                CO_SIZE(co)--;
                break;
            case '\\':
                *t++ = *s;
                CO_SIZE(co)--;
                break;
            default:
                *t++ = '\\';
                *t++ = *s;
                break;
            }
        } else {
            *t++ = *s;
        }
        s++;
    }
    *t = 0;
}

static void
co_scan_doublequoted_string(COStrObject *co)
{
    char *s, *t;
    char *end;

    s = t = co->co_sval;
    end = s + CO_SIZE(co);
    while (s < end) {
        if (*s == '\\') {
            s++;
            if (s >= end) {
                *t++ = '\\';
                break;
            }
            switch (*s) {
            case 'a':
                *t++ = '\a';
                CO_SIZE(co)--;
                break;
            case 'b':
                *t++ = '\b';
                CO_SIZE(co)--;
                break;
            case 'f':
                *t++ = '\f';
                CO_SIZE(co)--;
                break;
            case 'n':
                *t++ = '\n';
                CO_SIZE(co)--;
                break;
            case 'r':
                *t++ = '\r';
                CO_SIZE(co)--;
                break;
            case 't':
                *t++ = '\t';
                CO_SIZE(co)--;
                break;
            case 'v':
                *t++ = '\v';
                CO_SIZE(co)--;
                break;
            case '"':
                *t++ = '"';
                CO_SIZE(co)--;
                break;
            case '\\':
                *t++ = *s;
                CO_SIZE(co)--;
                break;
            case 'x':
                if (CO_IS_HEX(*(s+1)) && CO_IS_HEX(*(s+2))) {
                    char hex_buf[3] = {0, 0, 0};
                    CO_SIZE(co)--; /* for the 'x' */

                    hex_buf[0] = *(++s);
                    CO_SIZE(co)--;
                    hex_buf[1] = *(++s);
                    CO_SIZE(co)--;
                    *t++ = (char)strtol(hex_buf, NULL, 16);
                } else {
                    *t++ = '\\';
                    *t++ = *s;
                }
                break;
            default:
                /* check for octal digits */
                if (CO_IS_OCT(*s)) {
                    char octal_buf[4] = {0, 0, 0, 0};
                    octal_buf[0] = *s;
                    CO_SIZE(co)--;
                    if (CO_IS_OCT(*(s+1))) {
                        octal_buf[1] = *(++s);
                        CO_SIZE(co)--;
                        if (CO_IS_OCT(*(s+1))) {
                            octal_buf[2] = *(++s);
                            CO_SIZE(co)--;
                        }
                    }
                    *t++ = (char)strtol(octal_buf, NULL, 8);
                } else {
                    *t++ = '\\';
                    *t++ = *s;
                }
                break;
            }
        } else {
            *t++ = *s;
        }
        s++;
    }
    *t = 0;
}

void
scanner_init(struct arena *arena)
{
    scanner_globals.arena = arena;
}

int
scanner_setcode(char *code)
{
    scanner_globals.yy_cursor = code;
    scanner_globals.yy_limit = code + strlen(code);
    return 0;
}

int
scanner_lex(YYSTYPE *yylval)
{
    scanner_globals.yy_text = YYCURSOR;


#line 200 "scanner.c"
{
	YYCTYPE yych;
	goto yyc_SC_INIT;
/* *********************************** */
yyc_SC_INIT:
	{
		static const unsigned char yybm[] = {
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   6,   0,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  6,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			252, 252, 124, 124, 124, 124, 124, 124, 
			 60,  60,   4,   4,   4,   4,   4,   4, 
			  4,  44,  44,  44,  44,  44,  44,  12, 
			 12,  12,  12,  12,  12,  12,  12,  12, 
			 12,  12,  12,  12,  12,  12,  12,  12, 
			 12,  12,  12,   4,   4,   4,   4,  12, 
			  4,  44,  44,  44,  44,  44,  44,  12, 
			 12,  12,  12,  12,  12,  12,  12,  12, 
			 12,  12,  12,  12,  12,  12,  12,  12, 
			 12,  12,  12,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
			  4,   4,   4,   4,   4,   4,   4,   4, 
		};

		YYDEBUG(0, *YYCURSOR);
		YYFILL(9);
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '\t':
		case ' ':	goto yy41;
		case '\n':	goto yy43;
		case '!':	goto yy34;
		case '"':	goto yy21;
		case '#':	goto yy39;
		case '%':	goto yy32;
		case '\'':	goto yy23;
		case '(':
		case ')':
		case ',':
		case ':':
		case ';':
		case ']':
		case '^':
		case '{':
		case '}':
		case '~':	goto yy38;
		case '*':	goto yy30;
		case '+':	goto yy28;
		case '-':	goto yy29;
		case '.':	goto yy5;
		case '/':	goto yy31;
		case '0':	goto yy2;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy4;
		case '<':	goto yy26;
		case '=':	goto yy33;
		case '>':	goto yy27;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 'u':
		case 'v':
		case 'x':
		case 'y':
		case 'z':	goto yy25;
		case 'F':	goto yy19;
		case 'N':	goto yy17;
		case 'T':	goto yy18;
		case '[':	goto yy36;
		case 'b':	goto yy20;
		case 'c':	goto yy15;
		case 'd':	goto yy16;
		case 'e':	goto yy9;
		case 'f':	goto yy11;
		case 'i':	goto yy7;
		case 'l':	goto yy12;
		case 'r':	goto yy13;
		case 't':	goto yy14;
		case 'w':	goto yy10;
		default:	goto yy45;
		}
yy2:
		YYDEBUG(2, *YYCURSOR);
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 'O') {
			if (yych <= '9') {
				if (yych == '.') goto yy168;
				if (yych >= '0') goto yy172;
			} else {
				if (yych == 'B') goto yy174;
				if (yych >= 'O') goto yy175;
			}
		} else {
			if (yych <= 'b') {
				if (yych == 'X') goto yy176;
				if (yych >= 'b') goto yy174;
			} else {
				if (yych <= 'o') {
					if (yych >= 'o') goto yy175;
				} else {
					if (yych == 'x') goto yy176;
				}
			}
		}
yy3:
		YYDEBUG(3, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 210 "scanner.l"
		{
    char c = yytext[yyleng];
    yytext[yyleng] = '\0';
    yylval->node = node_new(scanner_globals.arena, NODE_CONST, NULL, NULL);
    yylval->node->u.o = COInt_FromString(yytext, NULL, 0);
    arena_addobject(scanner_globals.arena, yylval->node->u.o);
    yytext[yyleng] = c;
    return T_NUM;
}
#line 375 "scanner.c"
yy4:
		YYDEBUG(4, *YYCURSOR);
		yych = *(YYMARKER = ++YYCURSOR);
		goto yy171;
yy5:
		YYDEBUG(5, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 16) {
			goto yy165;
		}
yy6:
		YYDEBUG(6, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 422 "scanner.l"
		{
    return yytext[0];
}
#line 393 "scanner.c"
yy7:
		YYDEBUG(7, *YYCURSOR);
		++YYCURSOR;
		if ((yych = *YYCURSOR) == 'f') goto yy161;
		if (yych == 'n') goto yy163;
		goto yy79;
yy8:
		YYDEBUG(8, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 355 "scanner.l"
		{
    yylval->node = node_new(scanner_globals.arena, NODE_NAME, NULL, NULL);
    yylval->node->u.o = COStr_FromStringN(yytext, yyleng);
    arena_addobject(scanner_globals.arena, yylval->node->u.o);
    return T_NAME;
}
#line 410 "scanner.c"
yy9:
		YYDEBUG(9, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy151;
		if (yych == 'n') goto yy152;
		goto yy79;
yy10:
		YYDEBUG(10, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'h') goto yy146;
		goto yy79;
yy11:
		YYDEBUG(11, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= 'n') {
			if (yych == 'i') goto yy132;
			goto yy79;
		} else {
			if (yych <= 'o') goto yy133;
			if (yych == 'u') goto yy134;
			goto yy79;
		}
yy12:
		YYDEBUG(12, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy127;
		goto yy79;
yy13:
		YYDEBUG(13, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy121;
		goto yy79;
yy14:
		YYDEBUG(14, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'h') goto yy113;
		if (yych == 'r') goto yy114;
		goto yy79;
yy15:
		YYDEBUG(15, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy100;
		if (yych == 'o') goto yy101;
		goto yy79;
yy16:
		YYDEBUG(16, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy98;
		goto yy79;
yy17:
		YYDEBUG(17, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy94;
		goto yy79;
yy18:
		YYDEBUG(18, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy90;
		goto yy79;
yy19:
		YYDEBUG(19, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy85;
		goto yy79;
yy20:
		YYDEBUG(20, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy80;
		goto yy79;
yy21:
		YYDEBUG(21, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(22, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 314 "scanner.l"
		{
    while (1) {
        if (YYCURSOR > YYLIMIT) {
            break;
        }

        if (*YYCURSOR == '\"') {
            YYCURSOR++;
            yyleng = YYCURSOR - scanner_globals.yy_text;
            break;
        } else if (*YYCURSOR++ == '\\') {
            YYCURSOR++;
        }
    }
    yylval->node = node_new(scanner_globals.arena, NODE_CONST, NULL, NULL);
    yylval->node->u.o = COStr_FromStringN(yytext + 1, yyleng - 2);
    co_scan_doublequoted_string((COStrObject *)yylval->node->u.o);
    arena_addobject(scanner_globals.arena, yylval->node->u.o);
    return T_STRING;
}
#line 506 "scanner.c"
yy23:
		YYDEBUG(23, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(24, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 335 "scanner.l"
		{
    while (1) {
        if (YYCURSOR > YYLIMIT) {
            break;
        }
        if (*YYCURSOR == '\'') {
            YYCURSOR++;
            yyleng = YYCURSOR - scanner_globals.yy_text;
            break;
        } else if (*YYCURSOR++ == '\\') {
            YYCURSOR++;
        }
    } 
    yylval->node = node_new(scanner_globals.arena, NODE_CONST, NULL, NULL);
    yylval->node->u.o = COStr_FromStringN(yytext + 1, yyleng -2);
    co_scan_singlequoted_string((COStrObject *)yylval->node->u.o);
    arena_addobject(scanner_globals.arena, yylval->node->u.o);
    return T_STRING;
}
#line 532 "scanner.c"
yy25:
		YYDEBUG(25, *YYCURSOR);
		yych = *++YYCURSOR;
		goto yy79;
yy26:
		YYDEBUG(26, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= ';') goto yy6;
		if (yych <= '<') goto yy74;
		if (yych <= '=') goto yy72;
		goto yy6;
yy27:
		YYDEBUG(27, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= '<') goto yy6;
		if (yych <= '=') goto yy66;
		if (yych <= '>') goto yy68;
		goto yy6;
yy28:
		YYDEBUG(28, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '=') goto yy64;
		goto yy6;
yy29:
		YYDEBUG(29, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '=') goto yy62;
		goto yy6;
yy30:
		YYDEBUG(30, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '*') goto yy58;
		if (yych == '=') goto yy60;
		goto yy6;
yy31:
		YYDEBUG(31, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '=') goto yy56;
		goto yy6;
yy32:
		YYDEBUG(32, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '=') goto yy54;
		goto yy6;
yy33:
		YYDEBUG(33, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '=') goto yy52;
		goto yy6;
yy34:
		YYDEBUG(34, *YYCURSOR);
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy50;
yy35:
		YYDEBUG(35, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 438 "scanner.l"
		{
    return coerror(NULL, "invalid token: %s", yytext);
}
#line 593 "scanner.c"
yy36:
		YYDEBUG(36, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(37, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 414 "scanner.l"
		{
    return yytext[0];
}
#line 603 "scanner.c"
yy38:
		YYDEBUG(38, *YYCURSOR);
		yych = *++YYCURSOR;
		goto yy6;
yy39:
		YYDEBUG(39, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy49;
yy40:
		YYDEBUG(40, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 426 "scanner.l"
		{
    return T_COMMENT;
}
#line 620 "scanner.c"
yy41:
		YYDEBUG(41, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy47;
yy42:
		YYDEBUG(42, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 430 "scanner.l"
		{ 
    return T_WHITESPACE;
}
#line 633 "scanner.c"
yy43:
		YYDEBUG(43, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(44, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 434 "scanner.l"
		{
    return T_NEWLINE;
}
#line 643 "scanner.c"
yy45:
		YYDEBUG(45, *YYCURSOR);
		yych = *++YYCURSOR;
		goto yy35;
yy46:
		YYDEBUG(46, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy47:
		YYDEBUG(47, *YYCURSOR);
		if (yybm[0+yych] & 2) {
			goto yy46;
		}
		goto yy42;
yy48:
		YYDEBUG(48, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy49:
		YYDEBUG(49, *YYCURSOR);
		if (yybm[0+yych] & 4) {
			goto yy48;
		}
		goto yy40;
yy50:
		YYDEBUG(50, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(51, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 402 "scanner.l"
		{
    return T_NOT_EQUAL;
}
#line 679 "scanner.c"
yy52:
		YYDEBUG(52, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(53, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 398 "scanner.l"
		{
    return T_EQUAL;
}
#line 689 "scanner.c"
yy54:
		YYDEBUG(54, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(55, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 386 "scanner.l"
		{
    return T_MOD_ASSIGN;
}
#line 699 "scanner.c"
yy56:
		YYDEBUG(56, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(57, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 382 "scanner.l"
		{
    return T_DIV_ASSIGN;
}
#line 709 "scanner.c"
yy58:
		YYDEBUG(58, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(59, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 418 "scanner.l"
		{
    return T_POW;
}
#line 719 "scanner.c"
yy60:
		YYDEBUG(60, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(61, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 378 "scanner.l"
		{
    return T_MUL_ASSIGN;
}
#line 729 "scanner.c"
yy62:
		YYDEBUG(62, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(63, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 374 "scanner.l"
		{
    return T_SUB_ASSIGN;
}
#line 739 "scanner.c"
yy64:
		YYDEBUG(64, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(65, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 370 "scanner.l"
		{
    return T_ADD_ASSIGN;
}
#line 749 "scanner.c"
yy66:
		YYDEBUG(66, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(67, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 410 "scanner.l"
		{
    return T_GREATER_OR_EQUAL;
}
#line 759 "scanner.c"
yy68:
		YYDEBUG(68, *YYCURSOR);
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy70;
		YYDEBUG(69, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 366 "scanner.l"
		{
    return T_SR;
}
#line 770 "scanner.c"
yy70:
		YYDEBUG(70, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(71, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 394 "scanner.l"
		{
    return T_SR_ASSIGN;
}
#line 780 "scanner.c"
yy72:
		YYDEBUG(72, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(73, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 406 "scanner.l"
		{
    return T_SMALLER_OR_EQUAL;
}
#line 790 "scanner.c"
yy74:
		YYDEBUG(74, *YYCURSOR);
		++YYCURSOR;
		if ((yych = *YYCURSOR) == '=') goto yy76;
		YYDEBUG(75, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 362 "scanner.l"
		{
    return T_SL;
}
#line 801 "scanner.c"
yy76:
		YYDEBUG(76, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(77, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 390 "scanner.l"
		{
    return T_SL_ASSIGN;
}
#line 811 "scanner.c"
yy78:
		YYDEBUG(78, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy79:
		YYDEBUG(79, *YYCURSOR);
		if (yybm[0+yych] & 8) {
			goto yy78;
		}
		goto yy8;
yy80:
		YYDEBUG(80, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy79;
		YYDEBUG(81, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy79;
		YYDEBUG(82, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'k') goto yy79;
		YYDEBUG(83, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(84, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 306 "scanner.l"
		{
    return T_BREAK;
}
#line 844 "scanner.c"
yy85:
		YYDEBUG(85, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy79;
		YYDEBUG(86, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 's') goto yy79;
		YYDEBUG(87, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy79;
		YYDEBUG(88, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(89, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 300 "scanner.l"
		{
    yylval->node = node_new(scanner_globals.arena, NODE_CONST, NULL, NULL);
    yylval->node->u.o = CO_False;
    return T_BOOL;
}
#line 868 "scanner.c"
yy90:
		YYDEBUG(90, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy79;
		YYDEBUG(91, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy79;
		YYDEBUG(92, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(93, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 294 "scanner.l"
		{
    yylval->node = node_new(scanner_globals.arena, NODE_CONST, NULL, NULL);
    yylval->node->u.o = CO_True;
    return T_BOOL;
}
#line 889 "scanner.c"
yy94:
		YYDEBUG(94, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy79;
		YYDEBUG(95, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy79;
		YYDEBUG(96, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(97, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 288 "scanner.l"
		{
    yylval->node = node_new(scanner_globals.arena, NODE_CONST, NULL, NULL);
    yylval->node->u.o = CO_None;
    return T_NONE;
}
#line 910 "scanner.c"
yy98:
		YYDEBUG(98, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(99, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 284 "scanner.l"
		{
    return T_DO;
}
#line 923 "scanner.c"
yy100:
		YYDEBUG(100, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 't') goto yy109;
		goto yy79;
yy101:
		YYDEBUG(101, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy79;
		YYDEBUG(102, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 't') goto yy79;
		YYDEBUG(103, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy79;
		YYDEBUG(104, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy79;
		YYDEBUG(105, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy79;
		YYDEBUG(106, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy79;
		YYDEBUG(107, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(108, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 310 "scanner.l"
		{
    return T_CONTINUE;
}
#line 959 "scanner.c"
yy109:
		YYDEBUG(109, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy79;
		YYDEBUG(110, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'h') goto yy79;
		YYDEBUG(111, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(112, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 272 "scanner.l"
		{
    return T_CATCH;
}
#line 978 "scanner.c"
yy113:
		YYDEBUG(113, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy117;
		goto yy79;
yy114:
		YYDEBUG(114, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'y') goto yy79;
		YYDEBUG(115, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(116, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 268 "scanner.l"
		{
    return T_TRY;
}
#line 999 "scanner.c"
yy117:
		YYDEBUG(117, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy79;
		YYDEBUG(118, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'w') goto yy79;
		YYDEBUG(119, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(120, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 276 "scanner.l"
		{
    return T_THROW;
}
#line 1018 "scanner.c"
yy121:
		YYDEBUG(121, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 't') goto yy79;
		YYDEBUG(122, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy79;
		YYDEBUG(123, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'r') goto yy79;
		YYDEBUG(124, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy79;
		YYDEBUG(125, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(126, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 264 "scanner.l"
		{
    return T_RETURN;
}
#line 1043 "scanner.c"
yy127:
		YYDEBUG(127, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy79;
		YYDEBUG(128, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy79;
		YYDEBUG(129, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy79;
		YYDEBUG(130, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(131, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 247 "scanner.l"
		{
    return T_LOCAL;
}
#line 1065 "scanner.c"
yy132:
		YYDEBUG(132, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy140;
		goto yy79;
yy133:
		YYDEBUG(133, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy138;
		goto yy79;
yy134:
		YYDEBUG(134, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy79;
		YYDEBUG(135, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'c') goto yy79;
		YYDEBUG(136, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(137, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 243 "scanner.l"
		{
    return T_FUNC;
}
#line 1094 "scanner.c"
yy138:
		YYDEBUG(138, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(139, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 251 "scanner.l"
		{
    return T_FOR;
}
#line 1107 "scanner.c"
yy140:
		YYDEBUG(140, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'a') goto yy79;
		YYDEBUG(141, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy79;
		YYDEBUG(142, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy79;
		YYDEBUG(143, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'y') goto yy79;
		YYDEBUG(144, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(145, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 280 "scanner.l"
		{
    return T_FINALLY;
}
#line 1132 "scanner.c"
yy146:
		YYDEBUG(146, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy79;
		YYDEBUG(147, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'l') goto yy79;
		YYDEBUG(148, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'e') goto yy79;
		YYDEBUG(149, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(150, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 239 "scanner.l"
		{
    return T_WHILE;
}
#line 1154 "scanner.c"
yy151:
		YYDEBUG(151, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy156;
		if (yych == 's') goto yy155;
		goto yy79;
yy152:
		YYDEBUG(152, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'd') goto yy79;
		YYDEBUG(153, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(154, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 260 "scanner.l"
		{
    return T_END;
}
#line 1176 "scanner.c"
yy155:
		YYDEBUG(155, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy159;
		goto yy79;
yy156:
		YYDEBUG(156, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != 'f') goto yy79;
		YYDEBUG(157, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(158, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 235 "scanner.l"
		{
    return T_ELIF;
}
#line 1197 "scanner.c"
yy159:
		YYDEBUG(159, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(160, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 231 "scanner.l"
		{
    return T_ELSE;
}
#line 1210 "scanner.c"
yy161:
		YYDEBUG(161, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(162, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 227 "scanner.l"
		{
    return T_IF;
}
#line 1223 "scanner.c"
yy163:
		YYDEBUG(163, *YYCURSOR);
		++YYCURSOR;
		if (yybm[0+(yych = *YYCURSOR)] & 8) {
			goto yy78;
		}
		YYDEBUG(164, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 255 "scanner.l"
		{
    return T_IN;
}
#line 1236 "scanner.c"
yy165:
		YYDEBUG(165, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(166, *YYCURSOR);
		if (yybm[0+yych] & 16) {
			goto yy165;
		}
		YYDEBUG(167, *YYCURSOR);
		yyleng = YYCURSOR - scanner_globals.yy_text;
#line 220 "scanner.l"
		{
    yylval->node = node_new(scanner_globals.arena, NODE_CONST, NULL, NULL);
    yylval->node->u.o = COFloat_FromString(yytext);
    arena_addobject(scanner_globals.arena, yylval->node->u.o);
    return T_FNUM;
}
#line 1255 "scanner.c"
yy168:
		YYDEBUG(168, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 16) {
			goto yy165;
		}
yy169:
		YYDEBUG(169, *YYCURSOR);
		YYCURSOR = YYMARKER;
		goto yy3;
yy170:
		YYDEBUG(170, *YYCURSOR);
		YYMARKER = ++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
yy171:
		YYDEBUG(171, *YYCURSOR);
		if (yych == '.') goto yy168;
		if (yych <= '/') goto yy3;
		if (yych <= '9') goto yy170;
		goto yy3;
yy172:
		YYDEBUG(172, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
		YYDEBUG(173, *YYCURSOR);
		if (yych == '.') goto yy168;
		if (yych <= '/') goto yy169;
		if (yych <= '9') goto yy172;
		goto yy169;
yy174:
		YYDEBUG(174, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy181;
		}
		goto yy169;
yy175:
		YYDEBUG(175, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy179;
		}
		goto yy169;
yy176:
		YYDEBUG(176, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy177;
		}
		goto yy169;
yy177:
		YYDEBUG(177, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(178, *YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy177;
		}
		goto yy3;
yy179:
		YYDEBUG(179, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(180, *YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy179;
		}
		goto yy3;
yy181:
		YYDEBUG(181, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(182, *YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy181;
		}
		goto yy3;
	}
}
#line 441 "scanner.l"

}
